# Generated by Django 6.0.4 on 2026-04-25 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('product', models.CharField(choices=[('HDPE Granules', 'HDPE Granules'), ('LDPE Granules', 'LDPE Granules'), ('PP Granules', 'PP Granules'), ('Recycled Granules', 'Recycled Granules'), ('Other', 'Other')], max_length=50, verbose_name='Product')),
                ('message', models.TextField(blank=True, verbose_name='Message / Quantity Required')),
                ('quantity', models.CharField(blank=True, max_length=100, verbose_name='Quantity Required')),
                ('preferred_contact_time', models.CharField(blank=True, max_length=100, verbose_name='Preferred Contact Time')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('contacted', 'Contacted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('is_read', models.BooleanField(default=False, verbose_name='Mark as Read')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Enquiry',
                'verbose_name_plural': 'Enquiries',
                'db_table': 'enquiries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='enquiries_email_6571c6_idx'), models.Index(fields=['phone'], name='enquiries_phone_71dbea_idx'), models.Index(fields=['status'], name='enquiries_status_3b38ab_idx'), models.Index(fields=['created_at'], name='enquiries_created_87e45c_idx')],
            },
        ),
        migrations.CreateModel(
            name='EnquiryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(max_length=50)),
                ('sent_to', models.EmailField(max_length=254)),
                ('status', models.CharField(max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='Enquiry.enquiry')),
            ],
            options={
                'db_table': 'enquiry_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
